### ISSUE TITLE
[Request] FPS Limit should be settable from the GUI

### ISSUE THREAD

**Issue by MrGcGamer** [Sk1erLLC/Patcher#101]
Just a little request I have is that one should be able to set the fps limit (the one, one can set with `/patcher fps xxx`) from the GUI as well, cause I set mine to 60 upgraded my monitor, and was wondering, why I am unable to get higher frames although the minecraft cap was unlimited and the I couldn't find any fps related settings in the patcher GUI... basically just a little change to avoid confusion.

**Comment by SystemlessDev** [comment]
Feature added in [5de0a55](https://github.com/Sk1erLLC/Patcher/commit/5de0a55f6f3212333681b5da1b107ab3d7ab0a7c)
