### ISSUE TITLE
If "/" opened chat was cleaned, new "/" doesn't appear at start causing typing commands in chat appear as message

### ISSUE THREAD

**Issue by sermister1** [Sk1erLLC/Patcher#103]
When opening a chat again after sending a message, old message appears instead of the clean textbox(how to disable it?). But if "/" chat was cleaned, new "/" doesn't apprear at the start, causing 2nd command-chat button become useless.

**Comment by SystemlessDev** [comment]
Hey! I can't pick up what the issue here is. Are you able to rephrase it? Potentially it would be great with a recording showing the issue.

**Comment by sermister1** [comment]
I think that is how fullscreen change chat saving works. Closing the issue because i got familiar how it works.

**Comment by Sychic** [comment]
Is there a language barrier here? If the wording was unclear this could help us make it easier to understand for the future.
