### ISSUE TITLE
No way to disable the fps limit set by patcher

### ISSUE THREAD

**Issue by SystemlessDev** [Sk1erLLC/Patcher#106]
The user currently got no way to disable the fps limit patcher sets. This should be changed to disabling the feature whenever the user runs `/patcher fps` and/or `/patcher fps 0`.

**Comment by Sychic** [comment]
It already disables when running `/patcher fps 0`

https://github.com/Sk1erLLC/Patcher/blob/master/src/main/java/club/sk1er/patcher/mixins/features/MinecraftMixin_FpsLimit.java#L28-L30
https://github.com/Sk1erLLC/Patcher/blob/master/src/main/java/club/sk1er/patcher/commands/PatcherCommand.java#L187-L202
