### ISSUE TITLE
Even better hitboxes for crops 1.8.9

### ISSUE THREAD

**Issue by Mikecraft1224** [Sk1erLLC/Patcher#111]
Due to patcher in 1.8.9 only having the option to have 1.12 hitboxes for crops, it would be quite nice to have them be a full block.
I think since 1.16 they are like that but that also could be from a client like blc or lunar.
Crops like potato are 7 pixel short which is better than normal 1.8.9 but still able to be improved.

Especially for Skyblock this would be great.

**Comment by Sychic** [comment]
1.16 carrot hitbox vs 1.8.9 with patcher's hitboxes on
![1.16 carrot hitbox](https://user-images.githubusercontent.com/47618543/201451655-013f197f-95bb-4430-a6dc-5065185d3836.png) ![1.8.9 patcher](https://user-images.githubusercontent.com/47618543/201451873-9096a40a-7c6c-45a5-9f8d-58adadc6ae33.png) 
As you can see, they're both 9 pixels tall

Vanilla 1.8.9 for comparison
![1.8.9 vanilla](https://user-images.githubusercontent.com/47618543/201451835-873b1741-1de1-43ec-9ace-45bf631fb609.png)

1.16 potato hitbox vs 1.8.9 with patcher's hitboxes on
![1.16 potato hitbox](https://user-images.githubusercontent.com/47618543/201451694-37ad2722-09b1-460f-9fa0-db3ba4f40746.png) ![1.8.9 patcher](https://user-images.githubusercontent.com/47618543/201451950-1067924d-a40b-407b-8392-e75b844191b0.png)
Again, they're both 9 pixels tall.

Vanilla 1.8.9 for comparison
![1.8.9 vanilla](https://user-images.githubusercontent.com/47618543/201451985-91e1496d-e3ff-447b-b2e6-cb3d97cf4c8f.png)

It wouldn't make much sense to add something that isn't in Vanilla Minecraft.
