### ISSUE TITLE
/patcher name broken with name history api removal

### ISSUE THREAD

**Issue by willocn** [Sk1erLLC/Patcher#112]
The command does not work anymore. laby.net has an API that does not seem to be documented anywhere, but might be a suitable replacement

**Comment by DJtheRedstoner** [comment]
I think it would be most suitable to outright remove the command, as that respects mojang's decision.

**Comment by SystemlessDev** [comment]
Removed in [87e8473](https://github.com/Sk1erLLC/Patcher/commit/87e8473df9aeeb9c3a25766770c880f0bb63e7e0)
