### ISSUE TITLE
Some text elements are not scaled properly 

### ISSUE THREAD

**Issue by willocn** [Sk1erLLC/Patcher#113]
Elements like the ping display in tab and the glances above the hotbar are scaled poorly. They should be the same size as the rest of the text elements on the tablist.
![2022-09-15_14 18 05](https://user-images.githubusercontent.com/88864994/190490659-6f63baa0-2805-47b3-a8fe-1cfc1c45045c.png)
This is on a 4k display with large gui scale

**Comment by Sychic** [comment]
This is intended, they are meant to be drawn smaller than normal text to fit easier and differentiate from other text.

**Comment by willocn** [comment]
> This is intended, they are meant to be drawn smaller than normal text to fit easier and differentiate from other text.

It's completely unreadable at GUI scales where every other element on the screen is readable, maybe there should be an option for scaling then

**Comment by Sychic** [comment]
> It's completely unreadable at GUI scales where every other element on the screen is readable, maybe there should be an option for scaling then

It should scale with your set Minecraft GUI Scale.

**Comment by willocn** [comment]
It does, however like I said it is not readable at some scales, where all other text on the screen is. Another contributing factor is that the aliasing makes the numbers look worse at some GUI scales.
![image](https://user-images.githubusercontent.com/88864994/190494072-aca0888a-7b85-44df-bd59-4f14b53d21fd.png)
Result is that the features are borderline illegible at normal viewing distance and a smaller gui scale. This problem is resolved when those text elements match the size of the rest of the UI text.
