### ISSUE TITLE
Auto movement of character.

### ISSUE THREAD

**Issue by Anshul-004** [Sk1erLLC/Patcher#116]
The Character starts moving in a particular direction automatically when a specific set  of keys are pressed (for me it was ctrl+w+space) .
maybe this is caused due to some broken peice of code .

**Comment by Sychic** [comment]
I can't seem to reproduce this, do you have any more information on this issue?

**Comment by Anshul-004** [comment]
Thanks for  your interest , but it was due to another mod.  its fixed now
