### ISSUE TITLE
Improvement Suggestion

### ISSUE THREAD

**Issue by TripleCF** [Sk1erLLC/Patcher#124]
Wouldn't it make more sense and save resources to add a if statement to 'BlockNetherWartMixin_CropHeight.java' which checks wether the block is a nether wart? 

if(worldIn.getBlockState(pos).getBlock() == Blocks.nether_wart){
            CropUtilities.updateWartMaxY(worldIn, pos, worldIn.getBlockState(pos).getBlock());
}

Would save the client from calling the updateWartMaxY function every time.

**Comment by Apple26j** [comment]
Yes!
You can also make a pull request and get it fixed manually

**Comment by Sychic** [comment]
It's already only nether wart blocks.

**Comment by Apple26j** [comment]
Ok.
