### ISSUE TITLE
Disable Ground Arrows (Improvement)

### ISSUE THREAD

**Issue by CallMeArm** [Sk1erLLC/Patcher#125]
Currently the disable ground arrows feature works perfectly, but my suggestion is to make sure this option, when enabled, does not register the arrow hitboxes as well. Right now, when the option is enabled the arrow attached to the ground does not register, but if the arrow or projectile hitboxes are enabled, it shows the hitbox for the arrows attached to the ground, and it would be better if they could not show since the arrow is not present either. I will link a Minecraft screenshot to show what I mean.

Link: https://media.essential.gg/3f5bb049-577d-44df-17ea-f9e754e7ac00

**Comment by Apple26j** [comment]
I agree!

**Comment by Apple26j** [comment]
Why did Sk1erLLC delete my comment?
Did I say anything wrong?
It doesn't even tell me the reason

**Comment by Apple26j** [comment]
> Currently the disable ground arrows feature works perfectly, but my suggestion is to make sure this option, when enabled, does not register the arrow hitboxes as well. Right now, when the option is enabled the arrow attached to the ground does not register, but if the arrow or projectile hitboxes are enabled, it shows the hitbox for the arrows attached to the ground, and it would be better if they could not show since the arrow is not present either. I will link a Minecraft screenshot to show what I mean.
> 
> Link: https://media.essential.gg/3f5bb049-577d-44df-17ea-f9e754e7ac00

Agreed
