### ISSUE TITLE
Crash after launching without any mods

### ISSUE THREAD

**Issue by Felix14-v2** [Sk1erLLC/Patcher#127]
Hi, I tried to play with Patcher, but Minecraft crashes right after starting the game.
[[Demo]](https://youtu.be/LQ6Toa9xxU4)
[latest.log](https://github.com/Sk1erLLC/Patcher/files/10316901/latest.log)
[hs_err_pid1380.log](https://github.com/Sk1erLLC/Patcher/files/10316903/hs_err_pid1380.log)
[debug.log](https://github.com/Sk1erLLC/Patcher/files/10316902/debug.log)
I would really appreciate it if you could help me.

**Comment by SystemlessDev** [comment]
Hey! This issue is related to your graphics card software doing something weird. 
[Use intel's tool to update it to the latest version](https://www.intel.com/content/www/us/en/support/detect.html)

**Comment by Felix14-v2** [comment]
> Use intel's tool to update it to the latest version

I have already tried it, but it says that I have the latest driver.

**Comment by Felix14-v2** [comment]
@SystemlessDev , maybe I can disable some features to avoid broken things to load? Your performance solutions has no alternatives (excluding cheats), so if I could successfully launch it, it would help me a lot. If this is not possible, maybe you could advice me alternatives?
