### ISSUE TITLE
[1.8.9] Screenshot size zooms to bottom corner

### ISSUE THREAD

**Issue by agent-LuluDodo** [Sk1erLLC/Patcher#132]
## Description
Taking a screenshot with screenshot size set to 2x, 3x or 4x zooms to the bottom left corner of the screen.
![screenshot size 2x](https://user-images.githubusercontent.com/98981925/214950390-546e8c64-820c-4646-af04-507264548c38.png)
## Tested Versions
- preview OptiFine **1.8.9** HD U M6 pre2
- OptiFine **1.8.9** HD U M5
## Steps
1. Open settings
2. Click on 'Video Settings'
3. Click on 'Other'
4. Set 'Screenshot Size' to 2x, 3x or 4x
5. Take a screenshot

**Comment by Sychic** [comment]
Is this no longer an issue?

**Comment by agent-LuluDodo** [comment]
I somehow created the bug report on the wrong GitHub page. This is an issue with optifine not Patcher.

**Comment by Sychic** [comment]
It's only with optifine or does it happen with patcher and optifine?

**Comment by agent-LuluDodo** [comment]
Has absolutely nothing to do with Patcher. I confused the optifine GitHub page with this one, that's all.

**Comment by Sychic** [comment]
Ah alright, just making sure.
