### ISSUE TITLE
Invalid Mixin : RenderGlobalMixin_LimitVisGraphScan

### ISSUE THREAD

**Issue by Alexdoru** [Sk1erLLC/Patcher#136]
Boot up minecraft 1.8.9 with Patcher 1.8.6 and the Mixin debug args : `-Dmixin.debug=true -Dmixin.debug.verbose=true -Dmixin.debug.export=true -Dmixin.debug.countInjections=true -Dmixin.debug.strict=true`

It will print that the mixin doesn't apply

https://github.com/Sk1erLLC/Patcher/blob/2417efa7f6ab27d109b3d0a103c1819e074cfceb/src/main/java/club/sk1er/patcher/mixins/performance/RenderGlobalMixin_LimitVisGraphScan.java

     Action : APPLY                                                                                                                                              
      Mixin : club.sk1er.patcher.mixins.performance.RenderGlobalMixin_LimitVisGraphScan                                                                          
     Config : patcher.mixins.json                                                                                                                                
      Phase : DEFAULT                                                                                                                                            
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
     org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException                                                                                  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
     Injection validation failed: Callback method                                                                                                                
     patcher$setLimitScan(Lnet/minecraft/client/renderer/chunk/VisGraph;)Lnet/minecraft/client/renderer/chunk/VisGraph; in                                       
     patcher.mixins.json:performance.RenderGlobalMixin_LimitVisGraphScan expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using refmap             
     patcher.mixins.refmap.json [ -> PostInject ->                                                                                                               
     patcher.mixins.json:performance.RenderGlobalMixin_LimitVisGraphScan->@ModifyExpressionValue::patcher$setLimitScan(Lnet/minecraft/client/renderer/chunk/VisGr
     ph;)Lnet/minecraft/client/renderer/chunk/VisGraph;]                                                                                                         
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
     org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Injection validation failed: Callback method                                    
     patcher$setLimitScan(Lnet/minecraft/client/renderer/chunk/VisGraph;)Lnet/minecraft/client/renderer/chunk/VisGraph; in                                       
     patcher.mixins.json:performance.RenderGlobalMixin_LimitVisGraphScan expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using refmap             
     patcher.mixins.refmap.json [ -> PostInject ->                                                                                                               
     patcher.mixins.json:performance.RenderGlobalMixin_LimitVisGraphScan->@ModifyExpressionValue::patcher$setLimitScan(Lnet/minecraft/client/renderer/chunk/VisGr
     ph;)Lnet/minecraft/client/renderer/chunk/VisGraph;]

**Comment by Sychic** [comment]
Closed by #137
