### ISSUE TITLE
What it replaces

### ISSUE THREAD

**Issue by ztblat** [Sk1erLLC/Patcher#140]
Which modules it replaces, I need to know that I will not install to the same。

**Comment by Sychic** [comment]
Currently we have [this list](https://static.sk1er.club/patcher/duplicate_mods.json) but I'll add it to the readme.

**Comment by Sychic** [comment]
Completed in [e70db7c](https://github.com/Sk1erLLC/Patcher/commit/e70db7cdc9d0dbc116f276783b2b68937a0ce883)
