### ISSUE TITLE
Can I take some code from this? (with credits)

### ISSUE THREAD

**Issue by AppleClient** [Sk1erLLC/Patcher#159]
I will make sure to credit you all in my client!

**Comment by Sychic** [comment]
You must follow the license as outlined [here](https://github.com/Sk1erLLC/Patcher/blob/master/LICENSE.md) ([CC-BY NC SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/us/))

**Comment by AppleClient** [comment]
Thank you!

**Comment by AppleClient** [comment]
> You must follow the license as outlined [here](https://github.com/Sk1erLLC/Patcher/blob/master/LICENSE.md) ([CC-BY NC SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/us/))

**Comment by AppleClient** [comment]
> You must follow the license as outlined [here](https://github.com/Sk1erLLC/Patcher/blob/master/LICENSE.md) ([CC-BY NC SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/us/))

Hi! I am slightly confused.
The license in the Patcher project is different, and the one you linked me to is different.
Did you link the wrong license, or is the license in this project outdated

**Comment by Sychic** [comment]
Yes, I linked the wrong one but I believe they should say basically the same things.

**Comment by AppleClient** [comment]
Oh ok thx!
