### ISSUE TITLE
out of ess?

### ISSUE THREAD

**Issue by ralseilii** [Sk1erLLC/Patcher#160]
Will it detach from its dependence on ess in future versions? This is a great optimization mod, but I'm wondering if there's a way to only call the relevant ess code to achieve the optimization effect without needing the entire ess. After installation, it consumes a lot of memory, and ess touches on some sensitive topics.i used Not So Essential but not useful

**Comment by Sychic** [comment]
No, there are no plans to remove essential. Your memory usage is likely not due to essential and any further questions you have about what essential does may be asked through a support ticket in [our discord](https://discord.gg/essential).
