### ISSUE TITLE
NPE/Crash on opening Multiplayer window

### ISSUE THREAD

**Issue by Ninjune** [Sk1erLLC/Patcher#163]
Crashed due to a NullPointerException upon opening the multiplayer menu just after launching. Attached is the ss of error & full logs. Probably something to do with HUD caching. Doesn't happen again after relaunching, just happened once.

![image](https://github.com/Sk1erLLC/Patcher/assets/26883922/3e7bbeec-d2c1-4ea6-b898-1db419bf82b9)
[fml-client-latest.log](https://github.com/Sk1erLLC/Patcher/files/13397924/fml-client-latest.log)
[latest.log](https://github.com/Sk1erLLC/Patcher/files/13397925/latest.log)

**Comment by Sychic** [comment]
This looks unrelated to patcher as the error occurs during forge posting an event and not in patcher's code. If you believe this is a mistake, please reopen this issue.
