### ISSUE TITLE
Gui scale mod compatibility?

### ISSUE THREAD

**Issue by Resister0** [Sk1erLLC/Patcher#179]
You can basically change the scale of your gui down to exactly what you want it to be, even with commas.

On all other UI's it works fine, but with Essential / Patcher for 1.8.9, the place where you click is dis-aligned with the place the button visually is (only when using the gui scale mod ofc)

Example of the issue video link:
https://youtu.be/8prY2XB8BWU

The mod itself (with download in desc):
https://www.youtube.com/watch?v=pPnjWv6VXoU

**Comment by Sychic** [comment]
This looks like an issue with the original mod and not essential or patcher.
