### ISSUE TITLE
Void flicker fix support

### ISSUE THREAD

**Issue by Resister0** [Sk1erLLC/Patcher#180]
There is a mod that fixes flickering that sometimes happens when looking at the void from certain angles on some MC servers.
This mod fixes it. Would be cool if the same fix could be included in Patcher.

https://github.com/j-carin/VoidFlickerFix

**Comment by Sychic** [comment]
[This already exists.](https://github.com/Sk1erLLC/Patcher/blob/master/src/main/java/club/sk1er/patcher/mixins/bugfixes/WorldMixin_SkyHeight.java)
