### ISSUE TITLE
Maximum entity render distance is 64

### ISSUE THREAD

**Issue by solonovamax** [Sk1erLLC/Patcher#26]
It'd be nice if max entity render distance was increased from 64 to something like 256.
Or perhaps changed to use a % of the vanilla entity render distance, from 10% to 500% like how sodium does.

This would be useful for *extending* the vanilla entity render distance past what is normally achievable. I find the render distance of 64 to be quite limiting for various game modes such as bedwars on hypixel where you want to know if an enemy player is coming from a long distance away.

Relevant line(s):
https://github.com/Sk1erLLC/Patcher/blob/master/src/main/java/club/sk1er/patcher/config/PatcherConfig.java#L696-L728

I'll pr this when I get to my pc later, if you haven't already done it by then.

**Comment by asbyth** [comment]
This would not be allowed, should be fairly simple to assume why. You'd be seeing entities outside of the vanilla render distance.

**Comment by solonovamax** [comment]
That's understandable.
Would it at least be possible to increase the entity render distance to *use* the vanilla one?
For example: use vanilla render distance on players but decreased render distance on other entities.

**Comment by asbyth** [comment]
> 
> 
> That's understandable.
> Would it at least be possible to increase the entity render distance to _use_ the vanilla one?
> For example: use vanilla render distance on players but decreased render distance on other entities.

As of 1.6, there are 4 different categories. Global entities, hostile entities, passive entities, and players. All of these are 0-64

**Comment by solonovamax** [comment]
Vanilla entity render distance is greater than 64, afaik.
Because, if I disable the custom render distance, it will render entities way outside of the 64 block range

**Comment by Blurro** [comment]
> This would not be allowed, should be fairly simple to assume why. You'd be seeing entities outside of the vanilla render distance.

This issue is fixed if you install Fabric with no mods, or install Labymod, both are allowed clients on Hypixel. I use Forge with my own mod setup and can't seem to fix it though.
