### ISSUE TITLE
Name History Popup names can be too long for the container

### ISSUE THREAD

**Issue by ghost** [Sk1erLLC/Patcher#30]
![image](https://user-images.githubusercontent.com/36578995/136532959-579a86fc-f33e-49ed-ace4-8ac3298e0857.png)

Original concept should be followed better aswell, head is way too big (by Cubxity, use default Minecraft font)
![image](https://user-images.githubusercontent.com/36578995/136533039-e8cc85df-8e3b-42d8-b6e2-503a7265875e.png)

**Comment by Alexdoru** [comment]
this can be closed xd
