### ISSUE TITLE
Unable to start with OpenJ9 

### ISSUE THREAD

**Issue by TYOPXN360** [Sk1erLLC/Patcher#43]
Unable to start with OpenJ9

**Comment by SystemlessDev** [comment]
Works now. Tested with latest semeru build from IBM. Screenshot attached is the specific build.

https://developer.ibm.com/languages/java/semeru-runtimes/downloads/
![image](https://user-images.githubusercontent.com/45434286/181638258-0b975f1c-f9c7-4416-b793-ecd80397e961.png)
