### ISSUE TITLE
Lockups during world switching when Render Regions disabled

### ISSUE THREAD

**Issue by calcastor** [Sk1erLLC/Patcher#51]
This has been an issue I've been experiencing for awhile and it's taken me some time to narrow it down enough to make some sort of tangible report on it.

As a point of reference, I'm using Fedora 35 and run Minecraft using Java 8u312 available in its repos. I have done most of my testing related to this bug while only using Patcher and OptiFine as enabled mods, using the latest possible version of Forge for 1.8.9 and 1.12.2. I've previously tested for this bug using other distributions of Java (Azul Zulu JDK 8, BellSoft Liberica JDK 8) and did not have a different experience. I use a locally built copy of Patcher typically, but I've experienced this bug using the release distributed on sk1er.club.

Without OptiFine's Render Regions option enabled, it is virtually guaranteed that I experience ~10 second lockups when switching between servers after doing so at least once beforehand. This happens when switching between servers on larger network servers such as Hypixel, as well as between separate servers from the server list. I initially tied this to the font rendering optimisations, but I experience the issue with them disabled. I also thought that the optimised cloud rendering may be playing a part but that also does not seem to be the case as it also happens with that setting, or both that setting and the aforementioned font rendering opitmisations, disabled.

I typically try to leave Render Regions disabled as I tend to experience worse performance in a lot of situations using them. Nothing within my game logs points to anything about this unfortunately, but I can upload a log for each 1.8.9 and 1.12.2 if desired, I may be missing something.

This is not an issue I've encountered on 1.8.9 with OptiFine and Forge only. Disabling Patcher's fast world swapping error only results in it happening consistently even from game start, albeit with more even and consistently lower lockup times. I'd hoped to provide more info on this but I'm not quite knowledge enough on what's actually happening with Render Regions enabled and with what Patcher does that would be relevant to this issue, to narrow it down further.

**Comment by asbyth** [comment]
through some very quick testing, i can't reproduce this myself (windows 11), and neither can systemless (also on fedora 35)

**Comment by SystemlessDev** [comment]
Hey! What package are you using for the minecraft launcher? Could you send your patcher config (.minecraft/config/patcher.toml), as well as your graphics settings (.minecraft/options.txt) and lastly optifine settings (.minecraft/optionsof.txt). 

Also what about specs? Are you on wayland or X11? Amd, Intel or Novideo?

**Comment by calcastor** [comment]
> Hey! What package are you using for the minecraft launcher? Could you send your patcher config (.minecraft/config/patcher.toml), as well as your graphics settings (.minecraft/options.txt) and lastly optifine settings (.minecraft/optionsof.txt).

I've tested using PolyMC (and MultiMC, prior to switching to the former). I've been able to replicate this using the default launcher (Mojang provided binary rather than a package, launched from command line for testing).

[patcher.toml](https://gist.github.com/calcastor/19917af78757c713b3bd6544e08b493e#file-patcher-toml)
[.minecraft/options.txt](https://gist.github.com/calcastor/19917af78757c713b3bd6544e08b493e#file-options-txt)
[.minecraft/optionsof.txt](https://gist.github.com/calcastor/19917af78757c713b3bd6544e08b493e#file-optionsof-txt)

The above are using the default launcher, and default included runtime with latest Forge 1.12.2 and Patcher 1.8.0. Very little settings are changed from default. What I can say I noticed this time is that I only experienced the issue _after_ I changed my GUI scale from auto to my preferred setting when testing with the default launcher.

> Also what about specs? Are you on wayland or X11? Amd, Intel or Novideo?

I'm using GNOME under Wayland on an AMD laptop which lacks a discrete graphics card (AMD Ryzen 4500U). Some system side specifities I can note immediately are that I use a window manager level keyboard shortcut for full screen rather than MC's built-in full screen. This does not seem to be relevant to the issue as I can replicate it with either option.

**Comment by SystemlessDev** [comment]
I cannot reproduce the issue on my side. I am however using X11 with Novideo so that might explain it. I'll test it with my AMD laptop whenver I got time to dig it up. Do you have glthread enabled?

**Comment by calcastor** [comment]
> Do you have glthread enabled?

as in `mesa_glthread=true`? I do not, though I have tested it before; I actually get errors when attempting to use that setting with optimised font renderer enabled but I'd initially assumed it to be upstream issues in Mesa to be fixed in 22.0. In case it manages to be relevant to this issue somehow, here's the crash log when using `mesa_glthread=true`: [link](https://gist.github.com/calcastor/ac815fa6be2ec9a22d925c7cc5932f65). Will note that I was using a custom kernel build when testing in this instance, but I can reproduce it on Fedora default and have had the exact same error previously in Arch with a supported kernel in their repositories.
