### ISSUE TITLE
Issues with End Biome

### ISSUE THREAD

**Issue by Sychic** [Sk1erLLC/Patcher#56]
Specifically in skyblock, patcher causes the end biome to not render the sky as black, but rather as white.
Without Patcher: 
![image](https://user-images.githubusercontent.com/47618543/158081231-0de3dbc5-4c03-4763-ac1e-9ce728287c2b.png)
With Patcher: 
![image](https://user-images.githubusercontent.com/47618543/158081234-7787e5c7-d579-47d3-995c-235f9eca5f73.png)
How to reproduce the issue:
1. Install Patcher
2. Join Skyblock
3. Use an End Biome Stick to set part of your island to the end
4. Swap worlds so the biome updates
5. Look at the sky

**Comment by calcastor** [comment]
The culprit is [this mixin (WorldMixin_SkyColor](https://github.com/Sk1erLLC/Patcher/blob/master/src/main/java/club/sk1er/patcher/mixins/bugfixes/WorldMixin_SkyColor.java).

**Comment by wbxshiori** [comment]
This bug is not specifically in Skyblock, but even in singleplayer world as long as Patcher is active.

**Comment by wbxshiori** [comment]
The culprit has been identified almost 7 months ago, is that really too difficult to be fixed?

**Comment by Sychic** [comment]
While that mixin is responsible for returning the skycolor, that isn't the underlying issue. Currently we cache the sky color for each tick rather than re-calculating every frame. This calculation then doesn't take the player's current biome into account, leading to the sky color discrepancy.

**Comment by wbxshiori** [comment]
So is this bug easy or hard to be fixed? Do we just need to add the current biome to the calculation?
