### ISSUE TITLE
Sky does not turn darker when it rains

### ISSUE THREAD

**Issue by wbxshiori** [Sk1erLLC/Patcher#59]
Patcher causes the sky does not turn darker when the weather is rain or thunderstorm, no matter which world is active (e.g. singleplayer, Skyblock).
This bug may share the same culprit with issue #56, where End biome doesn't turn the sky to black.

Steps to reproduce:
1. Install Patcher
2. Open a world or join Skyblock
3. Make it rain (on Skyblock, use a Weather Stick or Weather Node, alternatively buy rain from Vanessa in Birch Park)
4. Look at the sky

With Patcher
![2022-03-30_08 20 46](https://user-images.githubusercontent.com/17959600/160727072-2016fb2a-7cde-4ca3-995b-4dfe9154693d.png)

Without Patcher
![2022-03-30_08 22 54](https://user-images.githubusercontent.com/17959600/160727085-189933dc-a794-48de-8c5e-836b86e3703e.png)

**Comment by DJtheRedstoner** [comment]
Fixed in 4832304
