### ISSUE TITLE
Healthbars not showing.

### ISSUE THREAD

**Issue by ArchLupus** [Sk1erLLC/Patcher#71]
On Hypixel Skyblock, where usually the health of mobs/minion full text would show through walls, it no longer does after intalling patcher
![image](https://user-images.githubusercontent.com/104752476/166368913-fec53861-e7ce-469e-bbeb-d2d42b74d6f2.png)

**Comment by Sychic** [comment]
It would appear you have either `Don't Cull Nametags` off or `Disable Armorstands` on. Try messing with your settings.

**Comment by ArchLupus** [comment]
> It would appear you have either `Don't Cull Nametags` off or `Disable Armorstands` on. Try messing with your settings.

Ive looked through the settings and i still cant find those, any idea where they would be?

**Comment by GamingGeek** [comment]
> > It would appear you have either `Don't Cull Nametags` off or `Disable Armorstands` on. Try messing with your settings.
> 
> Ive looked through the settings and i still cant find those, any idea where they would be?

Once you've got the settings open, you can just start typing to search for any settings

**Comment by ArchLupus** [comment]
> > > It would appear you have either `Don't Cull Nametags` off or `Disable Armorstands` on. Try messing with your settings.
> > 
> > 
> > Ive looked through the settings and i still cant find those, any idea where they would be?
> 
> Once you've got the settings open, you can just start typing to search for any settings

Worked thanks
