### ISSUE TITLE
Add Unfocused FPS support when out of a world

### ISSUE THREAD

**Issue by trytodupe** [Sk1erLLC/Patcher#86]
as title said, add unfocused fps for all the game, like main menu and server list and select world menu
not quite sure if its already there but when im not in a world and unfocused my gpu usage is just really high

**Comment by asbyth** [comment]
> as title said, add unfocused fps for all the game, like main menu and server list and select world menu not quite sure if its already there but when im not in a world and unfocused my gpu usage is just really high

already a thing in vanilla, by default the game puts you to 30 fps when you're not in a world, but Essential will increase that to 144 to make the character dragging feel a lot smoother.

**Comment by trytodupe** [comment]
> > as title said, add unfocused fps for all the game, like main menu and server list and select world menu not quite sure if its already there but when im not in a world and unfocused my gpu usage is just really high
> 
> already a thing in vanilla, by default the game puts you to 30 fps when you're not in a world, but Essential will increase that to 144 to make the character dragging feel a lot smoother.

is there a way to disable it

**Comment by asbyth** [comment]
> is there a way to disable it

nope

**Comment by trytodupe** [comment]
> > as title said, add unfocused fps for all the game, like main menu and server list and select world menu not quite sure if its already there but when im not in a world and unfocused my gpu usage is just really high
> 
> already a thing in vanilla, by default the game puts you to 30 fps when you're not in a world, but Essential will increase that to 144 to make the character dragging feel a lot smoother.

i was stupid yesterday
i meant to limit fps only when **unfocused**
why would you need 144 fps smooth animation when no one is looking at it
