### ISSUE TITLE
Patcher Resource Pack Bug

### ISSUE THREAD

**Issue by ooflol** [Sk1erLLC/Patcher#89]
So i use patcher lots and everytime i use it texture packs dont work
![image](https://user-images.githubusercontent.com/53439495/178827496-0d0ccc1a-d182-42e5-ac5c-b5d5e9dcc0f4.png)

**Comment by AspectOfJerry** [comment]
Can you give more details? What is not working? Applying the resource pack or what? Did you put it in the correct folder?

**Comment by SystemlessDev** [comment]
Not a patcher issue - Was a Essential issue that is now fixed.
