### ISSUE TITLE
[Suggestion] Add feature for "/block" in hypixel

### ISSUE THREAD

**Issue by yodaluca23** [Sk1erLLC/Patcher#91]
Please add a very simple toggle where when you type "/block <Player-Name>" it runs "/ignore add <Player-Name>"

**Comment by AspectOfJerry** [comment]
I mean… you can also just type "/ignore add <player>".

**Comment by yodaluca23** [comment]
> I mean… you can also just type "/ignore add". Also, what do you mean by toggle?

Yes but literally every time I want to block someone I do "/block" until I remember it's "/ignore add" and several of my friends have had similar experiences.

**Comment by GamingGeek** [comment]
Patcher is not a Hypixel focused mod and shouldn't really contain server specific features
