### ISSUE TITLE
AZERTY layout is still incomplete

### ISSUE THREAD

**Issue by Twenst** [Sk1erLLC/Patcher#92]
Hi, I've tried the AZERTY layout fix option and I only found one thing that is still not working.
Right now, it only fixes when you try to use your hotbar key when inside an inventory but it doesn't fix the bug that occurs when you are sneaking (SHIFT) and trying to use these keys.

- Indeed when no other keys are pressed, the 9 hotbar keys are
& é " ' ( - è _ ç
- When pressing SHIFT
1 2 3 4 5 6 7 8 9

**Comment by DeDiamondPro** [comment]
Hi, the feature is made to work with your controls set to 1-9 (see screenshot attached), that should fix it for you
![image](https://user-images.githubusercontent.com/67508414/183252034-cbf12d18-b815-4dfe-9b6a-9ae73025308f.png)
While reading your report I realized a different issue tho, there is French and Belgian azerty, currently it is made for Belgian azerty while the layout your describing is for French AZERTY, I'll make a quick fix that makes it so it supports both when I get the chance either today or tomorrow

**Comment by Sychic** [comment]
Closed by #102
