### ISSUE TITLE
Open to LAN replacement leaves blank space

### ISSUE THREAD

**Issue by GamingGeek** [Sk1erLLC/Patcher#94]
As Essential's `Invite Friends` button is no longer part of the buttons in the centre, a blank space is left when changing the Open to LAN replacement to anything other than default

![](https://imagedelivery.net/aG82t-qDLn415HP9HHoOeg/4009bbb5-01a7-44f1-f5d5-18a909962300/original)

**Comment by Sychic** [comment]
Resolved in 6e00f7c
