### ISSUE TITLE
Background not removed for Essential indicator with "Disable Nametag Boxes" enabled

### ISSUE THREAD

**Issue by GamingGeek** [Sk1erLLC/Patcher#95]
![](https://imagedelivery.net/aG82t-qDLn415HP9HHoOeg/bb133c5c-1153-4d76-7be6-7c531f037b00/original)

**Comment by Sychic** [comment]
Fixed with [696200b](https://github.com/Sk1erLLC/Patcher/commit/696200bba9bd0752cd64575ed974f2b9b72f175a)
